// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotificationService.Routing.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NotificationService.Routing.Migrations
{
    [DbContext(typeof(RoutingDbContext))]
    [Migration("20251207092152_InitialRoutingSchema")]
    partial class InitialRoutingSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NotificationService.Routing.Domain.Models.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Organization")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("organization");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("idx_contacts_email");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_contacts_active")
                        .HasFilter("is_active = true");

                    b.HasIndex("Organization")
                        .HasDatabaseName("idx_contacts_organization")
                        .HasFilter("organization IS NOT NULL");

                    b.ToTable("contacts", (string)null);
                });

            modelBuilder.Entity("NotificationService.Routing.Domain.Models.GroupMembership", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uuid")
                        .HasColumnName("contact_id");

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("added_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("AddedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("added_by");

                    b.HasKey("GroupId", "ContactId");

                    b.HasIndex("ContactId")
                        .HasDatabaseName("idx_group_memberships_contact");

                    b.ToTable("group_memberships", (string)null);
                });

            modelBuilder.Entity("NotificationService.Routing.Domain.Models.OutboundDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("channel");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uuid")
                        .HasColumnName("contact_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("delivered_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("failed_at");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("next_retry_at");

                    b.Property<Guid>("OutboundEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbound_event_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("role");

                    b.Property<Guid>("RoutingPolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("routing_policy_id");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Pending'");

                    b.HasKey("Id");

                    b.HasIndex("OutboundEventId")
                        .HasDatabaseName("idx_outbound_deliveries_event");

                    b.HasIndex("RoutingPolicyId");

                    b.HasIndex("ContactId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_outbound_deliveries_contact");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("idx_outbound_deliveries_pending")
                        .HasFilter("status IN ('Pending', 'Failed')");

                    b.ToTable("outbound_deliveries", (string)null);
                });

            modelBuilder.Entity("NotificationService.Routing.Domain.Models.OutboundEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Body")
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("ClientId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("client_id");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("processed_at");

                    b.Property<Guid?>("SagaId")
                        .HasColumnType("uuid")
                        .HasColumnName("saga_id");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("service");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("severity");

                    b.Property<string>("Subject")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("subject");

                    b.Property<string>("TemplateId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("template_id");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("topic");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_outbound_events_unprocessed")
                        .HasFilter("processed_at IS NULL");

                    b.HasIndex("SagaId")
                        .HasDatabaseName("idx_outbound_events_saga")
                        .HasFilter("saga_id IS NOT NULL");

                    b.HasIndex("ClientId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_outbound_events_client");

                    b.ToTable("outbound_events", (string)null);
                });

            modelBuilder.Entity("NotificationService.Routing.Domain.Models.RecipientGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ClientId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("idx_recipient_groups_client")
                        .HasFilter("client_id IS NOT NULL");

                    b.HasIndex("Name", "ClientId")
                        .IsUnique()
                        .HasDatabaseName("idx_recipient_groups_name_client");

                    b.ToTable("recipient_groups", (string)null);
                });

            modelBuilder.Entity("NotificationService.Routing.Domain.Models.RoutingPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("channel");

                    b.Property<string>("ClientId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<string>("MinSeverity")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("min_severity");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("priority");

                    b.Property<Guid>("RecipientGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_group_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("role");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("service");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("topic");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("RecipientGroupId");

                    b.HasIndex("Service", "Topic", "IsEnabled")
                        .HasDatabaseName("idx_routing_policies_client_fallback")
                        .HasFilter("client_id IS NULL AND is_enabled = true");

                    b.HasIndex("Service", "Topic", "ClientId", "IsEnabled")
                        .HasDatabaseName("idx_routing_policies_lookup")
                        .HasFilter("is_enabled = true");

                    b.ToTable("routing_policies", (string)null);
                });

            modelBuilder.Entity("NotificationService.Routing.Domain.Models.GroupMembership", b =>
                {
                    b.HasOne("NotificationService.Routing.Domain.Models.Contact", "Contact")
                        .WithMany("Memberships")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotificationService.Routing.Domain.Models.RecipientGroup", "Group")
                        .WithMany("Memberships")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("NotificationService.Routing.Domain.Models.OutboundDelivery", b =>
                {
                    b.HasOne("NotificationService.Routing.Domain.Models.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NotificationService.Routing.Domain.Models.OutboundEvent", "OutboundEvent")
                        .WithMany("Deliveries")
                        .HasForeignKey("OutboundEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotificationService.Routing.Domain.Models.RoutingPolicy", "RoutingPolicy")
                        .WithMany()
                        .HasForeignKey("RoutingPolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contact");

                    b.Navigation("OutboundEvent");

                    b.Navigation("RoutingPolicy");
                });

            modelBuilder.Entity("NotificationService.Routing.Domain.Models.RoutingPolicy", b =>
                {
                    b.HasOne("NotificationService.Routing.Domain.Models.RecipientGroup", "RecipientGroup")
                        .WithMany("Policies")
                        .HasForeignKey("RecipientGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RecipientGroup");
                });

            modelBuilder.Entity("NotificationService.Routing.Domain.Models.Contact", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("NotificationService.Routing.Domain.Models.OutboundEvent", b =>
                {
                    b.Navigation("Deliveries");
                });

            modelBuilder.Entity("NotificationService.Routing.Domain.Models.RecipientGroup", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("Policies");
                });
#pragma warning restore 612, 618
        }
    }
}
